# Generated by Django 3.2.4 on 2021-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
