# Generated by Django 3.2.4 on 2021-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orderitems_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
