# Generated by Django 3.2.4 on 2021-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='is_cart',
            field=models.BooleanField(default=0),
        ),
    ]
