# Generated by Django 3.2.4 on 2021-07-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='is_cart',
        ),
    ]
